// Jenkins must checkout the repository as subfolder MAIN
pipeline {
    agent {
        kubernetes {
            defaultContainer 'container-exec'
            yamlFile 'MAIN/.ci/KubernetesPod.yml'
        }
    }
    environment {
        DOCS_SOURCE_DIR = 'docs'
    }
    stages {
        stage('Install tools') {
            steps {
                dir("MAIN") {
                    sh 'apt update && apt install -y git make'
                    sh 'pip install -r .ci/docs/requirements_docs.txt'
                    sh 'pip install -r requirements.txt'  // we also need those because sphinx imports our code
                }
            }
        }
        stage('Build') {
            steps {
                dir("MAIN") {
                    sh './.ci/docs/build_docs.sh $DOCS_SOURCE_DIR'
                }
            }
        }
        stage('Publish') {
            environment {
                GIT_CREDENTIALS = credentials('github-sailor-user-token')
                GIT_CONFIG_USER_NAME = "${GIT_CREDENTIALS_USR}"
                GIT_CONFIG_USER_MAIL = "78745571+sailor-ci@users.noreply.github.com"
            }
            steps {
                sh 'git config --global credential.helper "!f() { echo username=\$GIT_CREDENTIALS_USR; echo password=\$GIT_CREDENTIALS_PSW; }; f"'
                dir("MAIN") {
                    sh './.ci/docs/publish_docs.sh $DOCS_SOURCE_DIR'
                }
            }
        }
    }
    post {
        always {
            step([$class: "GitHubCommitStatusSetter",]);
        }
        failure {
            slackSend (
                color: 'warning', 
                message: """Documentation build on main failed - ${env.JOB_NAME} [${env.BUILD_NUMBER}]

Please check the logs and take corrective action if necessary.
${env.BUILD_URL}/console
""")
        }
    }
}