name: Validation

on:
  push:
    branches: [main]

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9']

    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install pytest
          pip install -r requirements.txt

      - name: Run pytest
        run: pytest
